version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region ap-northeast-2 --no-include-email)
      - REPOSITORY_URI=629900478089.dkr.ecr.ap-northeast-2.amazonaws.com/forest-api
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t forest-api .
      - docker tag forest-api:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - printf 'image push success!'
      #- docker push $REPOSITORY_URI:$IMAGE_TAG
      #- echo Writing image definitions file...
      #- printf '[{"name":"nodeapp","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      # - cat imagedefinitions.json 
# artifacts:
#     files: imagedefinitions.json